from Arm.Stm32 import *

#env = Stm32f1md()
#haldir='stm32f103ze_redbull'
#env.setLinkfile( '/ld/stm32f103xe.ld' )

#env = Stm32f1md()
#haldir='stm32f103xb'
#env.setLinkfile( '/ld/stm32f103x8.ld' )
##env.setLinkfile( '/ld/stm32f103xb.ld' )

#env = Stm32f1md()
#haldir='stm32f103xb_pyeasycontrol'
#env.setLinkfile( '/ld/stm32f103xb.ld' )
#env.appendDriver(STM32_USB_FS_Driver())

env = Stm32f407xx()
haldir='stm32f407zg_eu'
env.setLinkfile( '/ld/stm32f407zg.ld' )

#env = Stm32f767xx()
#haldir='stm32f767zi_nucleo'
#env.setLinkfile( '/ld/stm32f767zi.ld' )

env.appendOptimizeFlags()


env.appendPath([
    '.',
    '../common',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% env.freertos_port,
    '/mcush',
    '/hal%s'% haldir,
])


env.appendGlobSource([
    '*.c',
    '../common/*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',  # normal
    '/libFreeRTOS/portable/GCC/%s/port.c'% env.freertos_port,
])


env.makeApp()

