from VEnvironment import *

#haldir='stm32f103ze_redbull'
#haldir='stm32f407zg_eu'

#env = loadHalConfig( haldir ).env
env = loadHalConfig( 'posix', append_rtos='POSIX' ).env
  
env.appendDefineFlags([
    'MCUSH_STACK_SIZE=10240',
    'VFS=1',
    'VFS_ROMFS=1',
    'STANDALONE=1',
    'USE_STRLWR=0', 
    'CELL_SEGSIZE=500',
    'CELL_NSEGMENT=1',
    'FIRST_CELLSEGS=1',
    ])

env.appendPath([
    '.',
])


env.appendGlobSource([
    '*.c',
])

env.appendLib(['m'])
env.makeApp()

