#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade f172c83ff51d+ on Fri Sep  1 15:55:20 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
import wx.stc
from wx.stc import StyledTextCtrl
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.RESIZE_BORDER | wx.SYSTEM_MENU | wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_tip = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("img/connect_controller.png", wx.BITMAP_TYPE_ANY))
        self.button_exit = wx.Button(self, wx.ID_EXIT, "")
        self.label_port = wx.StaticText(self, wx.ID_ANY, _("Port:"))
        self.combo_box_port = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_SORT)
        self.button_test_port = wx.Button(self, wx.ID_ANY, _("Test"))
        self.button_stop = wx.Button(self, wx.ID_STOP, "")
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.text_ctrl_script = StyledTextCtrl(self.notebook_1_pane_1, wx.ID_ANY)
        self.button_run = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("&Run"))
        self.button_reset = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Reset"))
        self.button_reboot = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Reboot"))
        self.button_load = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Load ..."))
        self.button_save_as = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Save as..."))
        self.spiffs = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.tree_ctrl_fs = wx.TreeCtrl(self.spiffs, wx.ID_ANY, style=wx.BORDER_SUNKEN | wx.NO_FULL_REPAINT_ON_RESIZE | wx.TR_HAS_BUTTONS | wx.TR_HIDE_ROOT | wx.TR_NO_BUTTONS | wx.TR_SINGLE)
        self.button_query = wx.Button(self.spiffs, wx.ID_ANY, _("&Query"))
        self.button_remove = wx.Button(self.spiffs, wx.ID_ANY, _("&Remove"))
        self.button_put_file = wx.Button(self.spiffs, wx.ID_ANY, _("&Put"))
        self.button_get_file = wx.Button(self.spiffs, wx.ID_ANY, _("&Get"))
        self.button_rename = wx.Button(self.spiffs, wx.ID_ANY, _("&Rename"))
        self.button_view = wx.Button(self.spiffs, wx.ID_ANY, _("&View"))
        self.bitmap_info = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("img/message.png", wx.BITMAP_TYPE_ANY))
        self.label_info = wx.StaticText(self, wx.ID_ANY, _("label_2"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnExit, self.button_exit)
        self.Bind(wx.EVT_BUTTON, self.OnTestPort, self.button_test_port)
        self.Bind(wx.EVT_BUTTON, self.OnStop, self.button_stop)
        self.Bind(wx.EVT_BUTTON, self.OnRun, self.button_run)
        self.Bind(wx.EVT_BUTTON, self.OnReset, self.button_reset)
        self.Bind(wx.EVT_BUTTON, self.OnReboot, self.button_reboot)
        self.Bind(wx.EVT_BUTTON, self.OnLoad, self.button_load)
        self.Bind(wx.EVT_BUTTON, self.OnSaveAs, self.button_save_as)
        self.Bind(wx.EVT_TREE_BEGIN_DRAG, self.OnFileBeginDrag, self.tree_ctrl_fs)
        self.Bind(wx.EVT_TREE_END_DRAG, self.OnFileEndDrag, self.tree_ctrl_fs)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.OnSelectFileItem, self.tree_ctrl_fs)
        self.Bind(wx.EVT_BUTTON, self.OnQuery, self.button_query)
        self.Bind(wx.EVT_BUTTON, self.OnRemove, self.button_remove)
        self.Bind(wx.EVT_BUTTON, self.OnPutFile, self.button_put_file)
        self.Bind(wx.EVT_BUTTON, self.OnGetFile, self.button_get_file)
        self.Bind(wx.EVT_BUTTON, self.OnRename, self.button_rename)
        self.Bind(wx.EVT_BUTTON, self.OnView, self.button_view)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.OnSwitchPage, self.notebook_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Mcush Debug Utility"))
        self.SetSize((990, 681))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.combo_box_port.SetMinSize((150, -1))
        self.button_test_port.SetMinSize((60, -1))
        self.button_stop.Hide()
        self.button_run.SetMinSize((150, 100))
        self.button_reset.SetMinSize((-1, 50))
        self.button_reboot.SetMinSize((-1, 50))
        self.button_load.SetMinSize((-1, 50))
        self.button_save_as.SetMinSize((-1, 50))
        self.notebook_1_pane_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.button_query.SetMinSize((200, 100))
        self.button_remove.SetMinSize((-1, 50))
        self.button_put_file.SetMinSize((-1, 50))
        self.button_get_file.SetMinSize((-1, 50))
        self.button_rename.SetMinSize((-1, 50))
        self.button_view.SetMinSize((-1, 50))
        self.spiffs.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.notebook_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_page = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_21 = wx.BoxSizer(wx.VERTICAL)
        sizer_20 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_adaptor = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_6.Add(self.bitmap_tip, 0, 0, 0)
        sizer_6.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_6.Add(self.button_exit, 0, 0, 0)
        sizer_4.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, 0, 0)
        sizer_adaptor.Add(self.label_port, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_adaptor.Add((10, 20), 0, 0, 0)
        sizer_adaptor.Add(self.combo_box_port, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_adaptor.Add((5, 20), 0, 0, 0)
        sizer_adaptor.Add(self.button_test_port, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_adaptor.Add((0, 0), 0, 0, 0)
        sizer_16.Add(sizer_adaptor, 0, wx.EXPAND, 0)
        sizer_16.Add((20, 20), 0, 0, 0)
        sizer_16.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_16.Add((20, 20), 0, 0, 0)
        sizer_16.Add(self.button_stop, 0, 0, 0)
        sizer_8.Add(sizer_16, 0, wx.EXPAND, 0)
        sizer_8.Add((20, 10), 0, 0, 0)
        sizer_5.Add((10, 20), 0, 0, 0)
        sizer_10.Add((20, 10), 0, 0, 0)
        sizer_10.Add(self.text_ctrl_script, 1, wx.EXPAND, 0)
        sizer_10.Add((20, 10), 0, 0, 0)
        sizer_5.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_5.Add((10, 20), 0, 0, 0)
        sizer_9.Add((20, 10), 0, 0, 0)
        sizer_9.Add(self.button_run, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 20), 0, 0, 0)
        sizer_9.Add(self.button_reset, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 20), 0, 0, 0)
        sizer_9.Add(self.button_reboot, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_9.Add((20, 10), 0, 0, 0)
        sizer_9.Add(self.button_load, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 10), 0, 0, 0)
        sizer_9.Add(self.button_save_as, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 10), 0, 0, 0)
        sizer_5.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_5.Add((10, 20), 0, 0, 0)
        self.notebook_1_pane_1.SetSizer(sizer_5)
        sizer_12.Add((10, 20), 0, 0, 0)
        sizer_14.Add((20, 10), 0, 0, 0)
        sizer_14.Add(self.tree_ctrl_fs, 1, wx.EXPAND, 0)
        sizer_14.Add((20, 10), 0, 0, 0)
        sizer_12.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_12.Add((10, 20), 0, 0, 0)
        sizer_13.Add((20, 10), 0, 0, 0)
        sizer_13.Add(self.button_query, 0, wx.EXPAND, 0)
        sizer_13.Add((20, 20), 0, 0, 0)
        sizer_20.Add(self.button_remove, 0, wx.EXPAND, 0)
        sizer_20.Add((20, 20), 0, 0, 0)
        sizer_20.Add(self.button_put_file, 0, wx.EXPAND, 0)
        sizer_20.Add((20, 20), 0, 0, 0)
        sizer_20.Add(self.button_get_file, 0, wx.EXPAND, 0)
        sizer_20.Add((20, 20), 0, 0, 0)
        sizer_20.Add((0, 0), 0, 0, 0)
        sizer_19.Add(sizer_20, 1, wx.EXPAND, 0)
        sizer_19.Add((20, 20), 0, 0, 0)
        sizer_21.Add(self.button_rename, 0, wx.EXPAND, 0)
        sizer_21.Add((20, 20), 0, 0, 0)
        sizer_21.Add(self.button_view, 0, wx.EXPAND, 0)
        sizer_21.Add((0, 0), 0, 0, 0)
        sizer_21.Add((0, 0), 0, 0, 0)
        sizer_21.Add((0, 0), 0, 0, 0)
        sizer_21.Add((0, 0), 0, 0, 0)
        sizer_21.Add((0, 0), 0, 0, 0)
        sizer_19.Add(sizer_21, 1, wx.EXPAND, 0)
        sizer_13.Add(sizer_19, 1, wx.EXPAND, 0)
        sizer_13.Add((20, 10), 0, 0, 0)
        sizer_12.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_12.Add((10, 20), 0, 0, 0)
        self.spiffs.SetSizer(sizer_12)
        self.notebook_1.AddPage(self.notebook_1_pane_1, _("Script mode"))
        self.notebook_1.AddPage(self.spiffs, _("File system"))
        sizer_8.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_8.Add((20, 10), 0, 0, 0)
        sizer_11.Add(self.bitmap_info, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_11.Add((5, 20), 0, 0, 0)
        sizer_11.Add(self.label_info, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_8.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_page.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_page, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        self.SetSize((990, 681))
        # end wxGlade

    def OnExit(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnExit' not implemented!")
        event.Skip()

    def OnTestPort(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnTestPort' not implemented!")
        event.Skip()

    def OnStop(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnStop' not implemented!")
        event.Skip()

    def OnRun(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnRun' not implemented!")
        event.Skip()

    def OnReset(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnReset' not implemented!")
        event.Skip()

    def OnReboot(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnReboot' not implemented!")
        event.Skip()

    def OnLoad(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnLoad' not implemented!")
        event.Skip()

    def OnSaveAs(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnSaveAs' not implemented!")
        event.Skip()

    def OnFileBeginDrag(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnFileBeginDrag' not implemented!")
        event.Skip()

    def OnFileEndDrag(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnFileEndDrag' not implemented!")
        event.Skip()

    def OnSelectFileItem(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnSelectFileItem' not implemented!")
        event.Skip()

    def OnQuery(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnQuery' not implemented!")
        event.Skip()

    def OnRemove(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnRemove' not implemented!")
        event.Skip()

    def OnPutFile(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnPutFile' not implemented!")
        event.Skip()

    def OnGetFile(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnGetFile' not implemented!")
        event.Skip()

    def OnRename(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnRename' not implemented!")
        event.Skip()

    def OnView(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnView' not implemented!")
        event.Skip()

    def OnSwitchPage(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnSwitchPage' not implemented!")
        event.Skip()

# end of class MyFrame

class MyViewFileDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyViewFileDialog.__init__
        kwds["style"] = wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.text_ctrl_data = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_PROCESS_ENTER | wx.TE_READONLY)
        self.button_close = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyViewFileDialog.__set_properties
        self.SetTitle(_("View file data"))
        self.SetSize((604, 439))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyViewFileDialog.__do_layout
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17.Add((20, 20), 0, 0, 0)
        sizer_18.Add((20, 20), 0, 0, 0)
        sizer_18.Add(self.text_ctrl_data, 1, wx.EXPAND, 0)
        sizer_18.Add((20, 10), 0, 0, 0)
        sizer_15.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_15.Add(self.button_close, 0, 0, 0)
        sizer_18.Add(sizer_15, 0, wx.EXPAND, 0)
        sizer_18.Add((20, 20), 0, 0, 0)
        sizer_17.Add(sizer_18, 1, wx.EXPAND, 0)
        sizer_17.Add((20, 20), 0, 0, 0)
        self.SetSizer(sizer_17)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MyViewFileDialog
