#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade f172c83ff51d+ on Tue Aug 22 08:10:22 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
import wx.stc
from wx.stc import StyledTextCtrl
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.RESIZE_BORDER | wx.SYSTEM_MENU | wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_tip = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("img/connect_controller.png", wx.BITMAP_TYPE_ANY))
        self.button_exit = wx.Button(self, wx.ID_EXIT, "")
        self.label_port = wx.StaticText(self, wx.ID_ANY, _("Port:"))
        self.combo_box_port = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_SORT)
        self.button_test_port = wx.Button(self, wx.ID_ANY, _("Test"))
        self.button_stop = wx.Button(self, wx.ID_STOP, "")
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.text_ctrl_script = StyledTextCtrl(self.notebook_1_pane_1, wx.ID_ANY)
        self.button_run = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("&Run"))
        self.button_reset = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Reset"))
        self.button_load = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Load ..."))
        self.button_save_as = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Save as..."))
        self.bitmap_info = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("img/message.png", wx.BITMAP_TYPE_ANY))
        self.label_info = wx.StaticText(self, wx.ID_ANY, _("label_2"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnExit, self.button_exit)
        self.Bind(wx.EVT_BUTTON, self.OnTestPort, self.button_test_port)
        self.Bind(wx.EVT_BUTTON, self.OnStop, self.button_stop)
        self.Bind(wx.EVT_BUTTON, self.OnRun, self.button_run)
        self.Bind(wx.EVT_BUTTON, self.OnReset, self.button_reset)
        self.Bind(wx.EVT_BUTTON, self.OnLoad, self.button_load)
        self.Bind(wx.EVT_BUTTON, self.OnSaveAs, self.button_save_as)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.OnSwitchPage, self.notebook_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Mcush Debug Utility"))
        self.SetSize((926, 564))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.combo_box_port.SetMinSize((150, -1))
        self.button_test_port.SetMinSize((60, -1))
        self.button_stop.Hide()
        self.button_run.SetMinSize((150, 100))
        self.button_reset.SetMinSize((-1, 50))
        self.button_load.SetMinSize((-1, 50))
        self.button_save_as.SetMinSize((-1, 50))
        self.notebook_1_pane_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.notebook_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_page = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_adaptor = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_6.Add(self.bitmap_tip, 0, 0, 0)
        sizer_6.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_6.Add(self.button_exit, 0, 0, 0)
        sizer_4.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, 0, 0)
        sizer_adaptor.Add(self.label_port, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_adaptor.Add((10, 20), 0, 0, 0)
        sizer_adaptor.Add(self.combo_box_port, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_adaptor.Add((5, 20), 0, 0, 0)
        sizer_adaptor.Add(self.button_test_port, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_adaptor.Add((0, 0), 0, 0, 0)
        sizer_16.Add(sizer_adaptor, 0, wx.EXPAND, 0)
        sizer_16.Add((20, 20), 0, 0, 0)
        sizer_16.Add((0, 0), 0, 0, 0)
        sizer_16.Add((20, 20), 0, 0, 0)
        sizer_16.Add(self.button_stop, 0, 0, 0)
        sizer_8.Add(sizer_16, 0, wx.EXPAND, 0)
        sizer_8.Add((20, 10), 0, 0, 0)
        sizer_5.Add((10, 20), 0, 0, 0)
        sizer_10.Add((20, 10), 0, 0, 0)
        sizer_10.Add(self.text_ctrl_script, 1, wx.EXPAND, 0)
        sizer_10.Add((20, 10), 0, 0, 0)
        sizer_5.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_5.Add((10, 20), 0, 0, 0)
        sizer_9.Add((20, 10), 0, 0, 0)
        sizer_9.Add(self.button_run, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 20), 0, 0, 0)
        sizer_9.Add(self.button_reset, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_9.Add((20, 10), 0, 0, 0)
        sizer_9.Add(self.button_load, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 10), 0, 0, 0)
        sizer_9.Add(self.button_save_as, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 10), 0, 0, 0)
        sizer_5.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_5.Add((10, 20), 0, 0, 0)
        self.notebook_1_pane_1.SetSizer(sizer_5)
        self.notebook_1.AddPage(self.notebook_1_pane_1, _("Script mode"))
        sizer_8.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_8.Add((20, 10), 0, 0, 0)
        sizer_11.Add(self.bitmap_info, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_11.Add((5, 20), 0, 0, 0)
        sizer_11.Add(self.label_info, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_8.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_page.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_page, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        self.SetSize((926, 564))
        # end wxGlade

    def OnExit(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnExit' not implemented!")
        event.Skip()

    def OnTestPort(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnTestPort' not implemented!")
        event.Skip()

    def OnStop(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnStop' not implemented!")
        event.Skip()

    def OnRun(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnRun' not implemented!")
        event.Skip()

    def OnReset(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnReset' not implemented!")
        event.Skip()

    def OnLoad(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnLoad' not implemented!")
        event.Skip()

    def OnSaveAs(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnSaveAs' not implemented!")
        event.Skip()

    def OnSwitchPage(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnSwitchPage' not implemented!")
        event.Skip()

# end of class MyFrame
