#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade f172c83ff51d+ on Tue Mar 21 13:29:30 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
from wx import InfoBar
# end wxGlade


class MemViewerFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MemViewerFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL | wx.TB_HORZ_TEXT)
        self.SetToolBar(self.frame_toolbar)
        self.frame_toolbar.AddLabelTool(1001, _("New"), wx.Bitmap("img/document-new.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(1002, _("Open"), wx.Bitmap("img/document-open.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(1003, _("Save"), wx.Bitmap("img/document-save.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(1004, _("Dump"), wx.Bitmap("img/document-export.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddSeparator()
        self.frame_toolbar.AddLabelTool(1005, _("Add"), wx.Bitmap("img/list-add.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(1006, _("Remove"), wx.Bitmap("img/list-remove.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(1007, _("Edit"), wx.Bitmap("img/document-properties.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddSeparator()
        self.frame_toolbar.AddLabelTool(1010, _("About"), wx.Bitmap("img/help-info.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.panel_main = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.bar_info = InfoBar(self.panel_main, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.OnNew, id=1001)
        self.Bind(wx.EVT_TOOL, self.OnOpen, id=1002)
        self.Bind(wx.EVT_TOOL, self.OnSave, id=1003)
        self.Bind(wx.EVT_TOOL, self.OnDump, id=1004)
        self.Bind(wx.EVT_TOOL, self.OnAdd, id=1005)
        self.Bind(wx.EVT_TOOL, self.OnRemove, id=1006)
        self.Bind(wx.EVT_TOOL, self.OnEdit, id=1007)
        self.Bind(wx.EVT_TOOL, self.OnAbout, id=1010)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MemViewerFrame.__set_properties
        self.SetTitle(_("Memory Viewer"))
        self.frame_toolbar.Realize()
        self.panel_main.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_main.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MemViewerFrame.__do_layout
        self.sizer_main = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_container = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        self.sizer_container.Add((0, 0), 0, 0, 0)
        sizer_3.Add(self.sizer_container, 1, wx.EXPAND, 0)
        sizer_3.Add(self.bar_info, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        self.panel_main.SetSizer(sizer_2)
        self.sizer_main.Add(self.panel_main, 1, wx.EXPAND, 0)
        self.SetSizer(self.sizer_main)
        self.sizer_main.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnNew(self, event):  # wxGlade: MemViewerFrame.<event_handler>
        print("Event handler 'OnNew' not implemented!")
        event.Skip()

    def OnOpen(self, event):  # wxGlade: MemViewerFrame.<event_handler>
        print("Event handler 'OnOpen' not implemented!")
        event.Skip()

    def OnSave(self, event):  # wxGlade: MemViewerFrame.<event_handler>
        print("Event handler 'OnSave' not implemented!")
        event.Skip()

    def OnDump(self, event):  # wxGlade: MemViewerFrame.<event_handler>
        print("Event handler 'OnDump' not implemented!")
        event.Skip()

    def OnAdd(self, event):  # wxGlade: MemViewerFrame.<event_handler>
        print("Event handler 'OnAdd' not implemented!")
        event.Skip()

    def OnRemove(self, event):  # wxGlade: MemViewerFrame.<event_handler>
        print("Event handler 'OnRemove' not implemented!")
        event.Skip()

    def OnEdit(self, event):  # wxGlade: MemViewerFrame.<event_handler>
        print("Event handler 'OnEdit' not implemented!")
        event.Skip()

    def OnAbout(self, event):  # wxGlade: MemViewerFrame.<event_handler>
        print("Event handler 'OnAbout' not implemented!")
        event.Skip()

# end of class MemViewerFrame
