from VEnvironment import *

#haldir='stm32f103ze_redbull'
haldir='stm32f103rb_pyeasycontrol'
#env = Stm32f407xx()

env = loadHalConfig( haldir ).env

env.appendOptimizeFlags()

env.appendDefineFlags( ['LED595_PORT=GPIOA', 'LED595_DAT=GPIO_Pin_0', 'LED595_SCK=GPIO_Pin_1', 'LED595_RCK=GPIO_Pin_2'] )
env.appendDefineFlags( ['OW_GPIO=GPIOB', 'OW_PIN=14'] )

env.appendPath([
    '.',
    '/libow',
])


env.appendGlobSource([
    '*.c',
    '/libow/*.c',
])


env.makeApp()

