from VEnvironment import *

haldir='stm32f103ze_redbull'
#haldir='stm32f103rb_pyeasycontrol'
#env = Stm32f407xx()

config = loadHalConfig( haldir )
env = config.env


env.appendOptimizeFlags()


env.appendPath([
    '.',
    '/libow',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% config.port,
    '/mcush',
    '/hal%s'% haldir,
])


env.appendGlobSource([
    '*.c',
    '/libow/*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',  # normal
    '/libFreeRTOS/portable/GCC/%s/port.c'% config.port,
])


env.makeApp()

