from VEnvironment import *
from Arm.Cortex import *

haldir='stm32f407zg_eu'

env = loadHalConfig( haldir ).env

env.appendDefineFlags(['MCUSH_STACK_SIZE=40000'])

env.appendPath([
    '.',
    '/CMSIS/Lib/GCC',
])


env.appendGlobSource([
    '*.c',
])


env.appendDriver( CMSIS_DSP_Driver(env._MCPU, fpu=True, source=True) )
#env.appendDriver( CMSIS_DSP_Driver(env._MCPU, fpu=True, source=False) )

env.appendLib(['m'])  # NOTE: add math lib after arm lib

env.makeApp()
