from VEnvironment import *
from Arm.Cortex import *

haldir='stm32f407zg_eu'


config = loadHalConfig( haldir )
env = config.env


env.appendDefineFlags(['MCUSH_STACK_SIZE=40000'])


env.appendPath([
    '.',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% config.port,
    '/mcush',
    '/hal%s'% haldir,
    '/CMSIS/Lib/GCC',
])


env.appendGlobSource([
    '*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',
    '/libFreeRTOS/portable/GCC/%s/port.c'% config.port,
])


env.appendDriver( CMSIS_DSP_Driver(env._MCPU, fpu=True, source=True) )
#env.appendDriver( CMSIS_DSP_Driver(env._MCPU, fpu=True, source=False) )

env.appendLib(['m'])  # NOTE: add math lib after arm lib

env.makeApp()
