from VEnvironment import *

haldir = 'stm32f103xb'

env = loadHalConfig( haldir ).env

#env.appendCompilerFlag(['-std=gnu90'])

env.appendCompilerFlag(['-fshort-wchar'])
env.appendLinkerFlag(['--specs=nano.specs'])
#env.appendLinkerFlag(['--no-wchar-size-warning'])
# TODO: do I need to rebuild the tool-chain?

# disable some commands and reduce flash size
env.appendDefineFlags( [
    #'USE_SHELL_PRINTF=0',
    'MCUSH_FREERTOS_PEEK_API=0',
    #'MCUSH_STACK_SIZE=10240',
    'SHELL_QUOTE_PARSE_ENALBE=0',
    'USE_CMD_DUMP=0',
    'USE_CMD_GPIO=0',
    'USE_CMD_HELP=0',
    'USE_CMD_LED=0',
    'USE_CMD_MAPI=0',
    'USE_CMD_MFILL=0',
    'USE_CMD_MKBUF=0',
    'USE_CMD_RESET=0',
    'USE_CMD_SCPI_IDN=0',
    'USE_CMD_SCPI_RST=0',
    'USE_CMD_SGPIO=0',
    'USE_CMD_SYSTEM=0',
    'USE_CMD_UPTIME=0',
    'USE_CMD_WAIT=0',
    'USE_CMD_WDG=0',
    'USE_CMD_WRITE=0',
    'USE_SHELL_EVAL_SSCANF=1',
    'configCHECK_FOR_STACK_OVERFLOW=0',
    'configTOTAL_HEAP_SIZE=10240',
    'configUSE_MUTEX=0',
    'configUSE_TIMERS=0',
    ] ) 


env.appendPath([
    '.',
])


env.appendGlobSource([
    '*.c',
])

env.makeApp()

