from VEnvironment import *

haldir='stm32f407zg_eu'
haldir='stm32f429ig_challenger'

env = loadHalConfig( haldir ).env

env.appendDefineFlags( [
    'configTIMER_TASK_STACK_DEPTH=1024',
    ] ) 


env.appendPath([
    '.',
])

env.appendGlobSource([
    '*.c',
])


env.makeApp()

