from VEnvironment import *

if haldir is None:
    # the last one is selected
    haldir='stm32f429ig_challenger'
    haldir='stm32f103cb_tiny_controller'
    haldir='stm32f407zg_eu'

env = loadHalConfig( haldir, use_spiffs=True ).env

env.appendDefineFlags( [
    'configTIMER_TASK_STACK_DEPTH=1024',
    ] ) 


env.appendPath([
    '.',
])

env.appendGlobSource([
    '*.c',
])


env.makeApp()

