from VEnvironment import *

if not haldir:
    haldir='stm32f407zg_eu'
    haldir='stm32f407ve_rabbit'

env = loadHalConfig( haldir, use_hal_driver=False, use_vfs=True, use_romfs=True, use_spiffs=True, use_eth=True ).env

env.appendDefineFlags( [ 'USE_LWIP_DEMO' ] )
#env.appendDefineFlags( [ 'USE_LWIP_HTTPSERVER_SIMPLE' ] )


env.appendDefineFlags( [
    'MCUSH_TASK_REGISTRY_SIZE=20',
    'SHELL_CMD_TABLE_LEN=8',
    'MCUSH_ROMFS_USER=1',
    'MCUSH_STACK_SIZE=10240',
    'configTIMER_TASK_STACK_DEPTH=200',
    'PING_USE_SOCKETS=0',
    #'CHECKSUM_BY_HARDWARE',
    'USE_CMD_PING=1',
    'USE_CMD_WGET=1',
    'USE_CMD_NC=1',
    'USE_NET_CHANGE_HOOK=1',
    ] ) 
    

#if not env.DEBUG:
#    env.appendDefineFlags( [
#        'LWIP_DEBUG=0',
#        ] )
#

env.appendPath([
    '.',
    '/liblwip/lwip-2.0.3/port',
    '/liblwip/lwip-2.0.3/port/Standalone',
    '/liblwip/lwip-2.0.3/src/include',
    '/liblwip/contrib-2.0.1/apps/socket_examples',
    '/liblwip/contrib-2.0.1/apps/httpserver',
    '/liblwip/contrib-2.0.1/apps/tcpecho',
    '/liblwip/contrib-2.0.1/apps/udpecho',
    '/liblwip/contrib-2.0.1/apps/shell',
    '/liblwip/lwip-2.0.3/src/include/lwip/apps',
    ])


env.appendGlobSource([
    '*.c',
    '/liblwip/lwip-2.0.3/src/core/*.c',
    '/liblwip/lwip-2.0.3/src/core/ipv4/*.c',
    '/liblwip/lwip-2.0.3/src/netif/ethernet.c',
    '/liblwip/lwip-2.0.3/src/api/*.c',
    '/liblwip/lwip-2.0.3/src/apps/tftp/*.c',
    '/liblwip/lwip-2.0.3/port/arch/*.c',
    '/liblwip/lwip-2.0.3/port/Standalone/*.c',
    #'/liblwip/contrib-2.0.1/apps/socket_examples/*.c',
    '/liblwip/contrib-2.0.1/apps/httpserver/httpserver-netconn.c',
    #'/liblwip/contrib-2.0.1/apps/ping/*.c',
    '/liblwip/contrib-2.0.1/apps/tcpecho/*.c',
    '/liblwip/contrib-2.0.1/apps/udpecho/*.c',
    '/liblwip/contrib-2.0.1/apps/shell/*.c',
    #'/liblwip/lwip-2.0.3/src/apps/mqtt/*.c',
    '/liblwip/lwip-2.0.3/src/apps/httpd/fs.c',
    '/liblwip/lwip-2.0.3/src/apps/httpd/httpd.c',
    '/liblwip/lwip-2.0.3/src/apps/netbiosns/netbiosns.c',
])


env.makeApp()

