from Arm import CortexM3
env = CortexM3()

if env.DEBUG:
    env.appendCompilerFlag( ['-g', '-O0'] )
else:
    env.appendCompilerFlag( ['-Os'] )
env.appendPath( ['.', 'include', 'portable/GCC/ARM_CM3'] )
env.appendGlobSource( ['*.c'] )
env.appendSource( ['portable/MemMang/heap_3.c'] )
env.appendSource( ['portable/GCC/ARM_CM3/port.c'] )
env.makeLib()

