from VEnvironment import *

haldir='stm32f103ze_redbull'
#haldir='stm32f103rb_pyeasycontrol'

env = loadHalConfig( haldir ).env

env.appendOptimizeFlags()

env.appendPath([
    '.',
])


env.appendGlobSource([
    '*.c',
])


env.makeApp()

