# MCUSH designed by Peng Shulin, all rights reserved.
from VEnvironment import *

haldir='stm32f407zg_eu'
haldir='stm32f407ve_mcudev'

env = loadHalConfig( haldir, use_hal_driver=False, use_vcp=False ).env

# disable some commands and reduce flash size
env.appendDefineFlags( [
    #'MCUSH_STACK_SIZE=10240',
    ] ) 

if not env.DEBUG:
    env.appendDefineFlags( [ 'HAL_WDG_ENABLE=1' ] ) 


env.appendPath([
    '.',
])


env.appendGlobSource([
    '*.c',
])



env.makeApp()

