from VEnvironment import *

haldir='stm32f407zg_eu'
haldir='stm32f407ve_mcudev'

env = loadHalConfig( haldir ).env

# disable some commands and reduce flash size
env.appendDefineFlags( [
    #'MCUSH_STACK_SIZE=10240',
    ] ) 

env.appendPath([
    '.',
])


env.appendGlobSource([
    '*.c',
])



env.makeApp()

