from VEnvironment import *

haldir='stm32f407zg_eu'
config = loadHalConfig( haldir )
env = config.env

# disable some commands and reduce flash size
env.appendDefineFlags( [
    #'MCUSH_STACK_SIZE=10240',
    ] ) 


env.appendPath([
    '.',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% config.port,
    '/mcush',
    '/hal%s'% haldir,
])


env.appendGlobSource([
    '*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',
    '/libFreeRTOS/portable/GCC/%s/port.c'% config.port,
])



env.makeApp()

