from VEnvironment import *
from Arm.Stm32 import *

haldir='stm32f407zg_eu'

env = loadHalConfig( haldir ).env

env.appendDefineFlags( [
    'MCUSH_STACK_SIZE=10240',
    'GUI_ALLOC_SIZE=16000',
    'GUI_SUPPORT_MEMDEV=1',
    'SHOW_GUIDEMO_BARGRAPH=1',
    'SHOW_GUIDEMO_RADIALMENU=1',
    'configTIMER_TASK_STACK_DEPTH=2048',
    ] ) 

env.appendPath([
    '.',
    '/hal%s/emwin_driver'% env.haldir,
    'GUIDemo',
])

env.appendGlobSource([
    '*.c',
    '/hal%s/emwin_driver/*.c'% env.haldir,
    'GUIDemo/*.c',
])

env.appendSource([
    '/ST/STemWin/OS/GUI_X_FreeRTOS.c',
])

env.appendDriver(STemWin(os=False))
env.makeApp()

