from VEnvironment import *
from Arm.Stm32 import *

haldir='stm32f407zg_eu'
config = loadHalConfig( haldir )
env = config.env

env.appendDefineFlags( [
    'MCUSH_STACK_SIZE=10240',
    'GUI_ALLOC_SIZE=16000',
    'GUI_SUPPORT_MEMDEV=1',
    'SHOW_GUIDEMO_BARGRAPH=1',
    'SHOW_GUIDEMO_RADIALMENU=1',
    'configTIMER_TASK_STACK_DEPTH=2048',
    ] ) 

env.appendPath([
    '.',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% config.port,
    '/mcush',
    '/hal%s'% haldir,
    '/hal%s/emwin_driver'% haldir,
    'GUIDemo',
])


env.appendGlobSource([
    '*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/hal%s/emwin_driver/*.c'% haldir,
    'GUIDemo/*.c',
])

env.appendSource([
    '/ST/STemWin/OS/GUI_X_FreeRTOS.c',
])

env.appendGlobSource([
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',  # normal
    '/libFreeRTOS/portable/GCC/%s/port.c'% config.port,
    ])

env.appendDriver(STemWin(os=False))
env.makeApp()

