from VEnvironment import *

#haldir='stm32f103ze_redbull'
haldir='stm32f407zg_eu'

env = loadHalConfig( haldir ).env

env.appendDefineFlags([
    'MCUSH_STACK_SIZE=10240',
    ])

env.appendPath([
    '.',
    #'/libpicolisp',
])


env.appendGlobSource([
    '*.c',
    #'/libpicolisp/*.c',
])


env.appendLib(['m'])
env.makeApp()

