from VEnvironment import *

haldir='stm32f103rb_pyeasycontrol'

config = loadHalConfig( haldir )
env = config.env


env.appendOptimizeFlags()

env.appendPath([
    '.',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% config.port,
    '/mcush',
    '/hal%s'% haldir,
])


env.appendGlobSource([
    '*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',
    '/libFreeRTOS/portable/GCC/%s/port.c'% config.port,
])

env.appendDefineFlags( ['CONFIG_TICK_RATE_HZ=1000'] )

env.appendLib( ['m'] )

env.makeApp()

