from VEnvironment import *

haldir='stm32f103rb_pyeasycontrol'

env = loadHalConfig( haldir ).env

env.appendOptimizeFlags()

env.appendPath([
    '.',
])


env.appendGlobSource([
    '*.c',
])

env.appendDefineFlags( ['CONFIG_TICK_RATE_HZ=1000'] )

env.appendLib( ['m'] )

env.makeApp()

