from VEnvironment import *

#haldir='stm32f103ze_redbull'
#haldir='stm32f103rb_pyeasycontrol'
haldir='stm32f407zg_eu'
#haldir='stm32f767zi_nucleo'

env = loadHalConfig( haldir ).env

env.appendOptimizeFlags()

env.appendPath([
    '.',
])


env.appendGlobSource([
    '*.c',
])


env.makeApp()

