from VEnvironment import *

haldir='stm32f407zg_eu'

env = loadHalConfig( haldir ).env


env.appendDefineFlags(['MCUSH_STACK_SIZE=10000'])

env.appendPath([
    '.',
    '/libcjson',
    '/CMSIS/Lib/GCC',
])


env.appendGlobSource([
    '*.c',
    '/libcjson/cJSON.c',
])


env.appendLib(['m'])
env.makeApp()
