from VEnvironment import *

haldir='stm32f407zg_eu'

config = loadHalConfig( haldir )
env = config.env


env.appendDefineFlags(['MCUSH_STACK_SIZE=10000'])


env.appendPath([
    '.',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% config.port,
    '/mcush',
    '/libcjson',
    '/hal%s'% haldir,
    '/CMSIS/Lib/GCC',
])


env.appendGlobSource([
    '*.c',
    '/mcush/*.c',
    '/libcjson/cJSON.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',
    '/libFreeRTOS/portable/GCC/%s/port.c'% config.port,
])


env.appendLib(['m'])
env.makeApp()
