from Arm import *

env = CortexM4(cmsis_inc=False)
env.setLinkfile( '/ld/lpc4337_m4_min.ld' )

env.appendDefineFlags( [
    'CORE_M4', 
    'ARM_MATH_CM4',
    '__FPU_PRESENT',
] )

env.appendPath([
    '/NXP/lpcopen/lpc_chip_43xx/inc/',
    '/NXP/lpcopen/lpc_board_nxp_lpcxpresso_4337/inc/',
])


env.appendGlobSource([
    'stub.c',
    'src/*.c',
    '/NXP/lpcopen/lpc_chip_43xx/src/*.c',
    '/NXP/lpcopen/lpc_board_nxp_lpcxpresso_4337/src/*.c',
])

env.makeApp()

