from Arm.Stm32 import *
env = Stm32f1md()
env.appendDriver(STM3210B_EVAL_Driver())
env.appendDriver(STM32_USB_FS_Driver())
env.setLinkfile( '/ld/stm32f103xb.ld' )
#env.appendCompilerFlag( ['-DDATA_IN_ExtSRAM'] )
if env.DEBUG:
    env.appendCompilerFlag( ['-O0', '-g'] )
else:
    env.appendCompilerFlag( ['-Os'] )
env.appendPath( ['inc'] )
env.appendPath( ['.'] )
env.appendGlobSource( ['src/*.c'], 'src/system_*.c' ) 
#print env.source
env.makeApp()

