from Arm.Stm32 import *

env = Stm32f407xx()
haldir='stm32f407zg_eu'
env.setLinkfile( '/ld/stm32f407zg_min.ld' )
port = 'ARM_CM4F'


env.appendDefineFlags( [
    #'MCUSH_STACK_SIZE=10240',
    'MCUSH_TASK_REGISTRY_SIZE=20',
    ] ) 


env.appendPath([
    '.',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% port,
    '/mcush',
    '/hal%s'% haldir,
])


env.appendGlobSource([
    '*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    #'/libFreeRTOS/portable/MemMang/heap_1.c',  # simple malloc, not free
    #'/libFreeRTOS/portable/MemMang/heap_2.c',  # simple malloc, with free, not combine
    '/libFreeRTOS/portable/MemMang/heap_3.c',  # normal
    '/libFreeRTOS/portable/GCC/%s/port.c'% port,
])

env.makeApp()

