from VEnvironment import *

haldir='stm32f407zg_eu'

env = loadHalConfig( haldir ).env

env.appendDefineFlags( [
    #'MCUSH_STACK_SIZE=10240',
    'MCUSH_TASK_REGISTRY_SIZE=20',
    ] ) 

env.appendPath([
    '.',
])


env.appendGlobSource([
    '*.c',
])

env.makeApp()

