from Arm.Stm32 import *

#env = Stm32f1md()
#haldir='stm32f103xb'
#env.setLinkfile( '/ld/stm32f103xc_min.ld' )
#port = 'ARM_CM3'

env = Stm32f1hd()
haldir='stm32f103ze_redbull'
env.setLinkfile( '/ld/stm32f103xe_min.ld' )
port = 'ARM_CM3'

#env = Stm32f407xx()
#haldir='stm32f407zg_eu'
#env.setLinkfile( '/ld/stm32f407zg_min.ld' )
#port = 'ARM_CM4F'

#env = Stm32f767xx()
#haldir='stm32f767zi_nucleo'
#env.setLinkfile( '/ld/stm32f767zi_min.ld' )
#port = 'ARM_CM7'

env.appendDefineFlags([
    'MCUSH_STACK_SIZE=10240',
    #'LUA_32BITS'
    ])


env.appendPath([
    '.',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% port,
    '/mcush',
    '/hal%s'% haldir,
    '/liblua',
])


env.appendGlobSource([
    '*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',
    '/libFreeRTOS/portable/GCC/%s/port.c'% port,
    '/liblua/*.c',
])
env.appendLib(['m'])
env.makeApp()

