from VEnvironment import *

haldir='stm32f103ze_redbull'
#haldir='stm32f407zg_eu'

config = loadHalConfig( haldir )
env = config.env

env.appendDefineFlags([
    'MCUSH_STACK_SIZE=10240',
    #'LUA_32BITS',
    'USE_SHELL_PRINTF2=0',
    ])


env.appendPath([
    '.',
    '/libFreeRTOS',
    '/libFreeRTOS/include',
    '/libFreeRTOS/portable/GCC/%s'% config.port,
    '/mcush',
    '/hal%s'% haldir,
    '/liblua',
])


env.appendGlobSource([
    '*.c',
    '/mcush/*.c',
    '/hal%s/*.c'% haldir,
    '/libFreeRTOS/*.c',
    '/libFreeRTOS/portable/MemMang/heap_3.c',
    '/libFreeRTOS/portable/GCC/%s/port.c'% config.port,
    '/liblua/*.c',
])

env.makeApp()

