from VEnvironment import *

haldir='stm32f407zg_eu'
haldir='stm32f103ze_redbull'

env = loadHalConfig( haldir ).env

env.appendDefineFlags([
    'MCUSH_STACK_SIZE=10240',
    #'LUA_32BITS',
    'USE_SHELL_PRINTF2=0',
    ])

env.appendPath([
    '.',
    '/liblua',
])


env.appendGlobSource([
    '*.c',
    '/liblua/*.c',
])

env.makeApp()

