from Arm.Lpc import *

class Lpc4337withoutCMSIS( Lpc4337 ):
    INCLUDE_CMSIS=False

env = Lpc4337withoutCMSIS(startup_driver=False)
env.setLinkfile( '/ld/lpc4337_m4_min.ld' )

env.appendDefineFlags( [
    #'__USE_CMSIS',
    #'__VFP_FP__',
    #'__FPU_PRESENT',
    #'ARM_MATH_CM4',
] )

env.appendPath([
    #'inc',
    '/NXP/lpcopen/lpc_chip_43xx/inc/',
    '/NXP/lpcopen/lpc_board_nxp_lpcxpresso_4337/inc/',
])


env.appendGlobSource([
    '*.c',
    'src/*.c',
    '/NXP/lpcopen/lpc_chip_43xx/src/*.c',
    '/NXP/lpcopen/lpc_board_nxp_lpcxpresso_4337/src/*.c',
])

env.makeApp()

