from Arm.Cortex import *
from Arm.Stm32 import *
from VEnvironment import *

env = Stm32M4()
env.DEBUG = False

env.setLinkfile( '/ld/stm32f407xg_sram.ld' )

env.appendDefineFlags(['STM32F40_41xxx'])

env.appendPath([
    '/CMSIS/Device/ST/STM32F4xx/Include',
    '/ST/STM32F4xx_StdPeriph_Driver/inc',
])


env.appendGlobSource([
    'main.c',
    'startup_stm32f40_41xxx.s',
    '/ST/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c',
    '/ST/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c',
])


env.appendLinkFlag(['-Wl,--entry=Reset_Handler'])
env.appendOptimizeFlags(['-O3'])
env.makeApp()

